name: verify
on:
  push:
    branches:
      - master
    paths:
      - '.github/**'
      - '.verify-helper/**'
      - 'src/code/**'
      - 'src/doc_md/**'
      - 'src/test_cpverifier/**'
  pull_request:
    branches:
      - master
    paths:
      - '.github/**'
      - '.verify-helper/**'
      - 'src/code/**'
      - 'src/doc_md/**'
      - 'src/test_cpverifier/**'
  workflow_dispatch:
    inputs:
      ignore_prev_result:
        type: boolean
        default: false

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: ${{ github.head_ref || 'x' }}-${{ github.workflow }}-${{ github.ref }}-verify
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: ["huge"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up competitive-verifier
        uses: competitive-verifier/actions/setup@v2
        with:
          package: competitive-verifier==3.3.0.dev0 
          cache-pip: true

      - name: oj-resolve
        uses: competitive-verifier/actions/oj-resolve@v2
        env:
          VERIFY_EXCLUDE: ${{ matrix.type == 'huge' && 'src/test_cpverifier/' || (matrix.type == 'normal' && 'src/test_cpverifier_huge/' || 'src/tinplate/') }}
        with:
          output-path: verify_files.json
          include: |
                src/code/
                src/doc_md/
                src/test_cpverifier/
                src/test_cpverifier_huge/
          exclude: |
                libs/
                .github/
                $VERIFY_EXCLUDE
          config: .verify-helper/config.toml
      - name: parse-doxygen
        uses: competitive-verifier/actions/parse-doxygen@v2
        with:
          verify-files: verify_files.json

      - name: Upload verify_files.json
        uses: competitive-verifier/actions/upload-verify-artifact@v2
        with:
          file: verify_files.json
          artifact-name: ${{ runner.os }}-verify-files-${{ matrix.type }}-json

      - name: Check bundled
        id: test-bundled
        if: ${{ matrix.type == 'all' }}
        run: |
          echo "count=$(find .competitive-verifier/bundled/ -type f | wc -l)" >> $GITHUB_OUTPUT
      - name: Upload bundled
        uses: actions/upload-artifact@v4
        if: steps.test-bundled.outputs.count > 0
        with:
          name: Bundled-${{ runner.os }}
          path: .competitive-verifier/bundled
          retention-days: 1

  verify:
    runs-on: ubuntu-latest
    needs: [setup]
    env:
      SPLIT_SIZE: 16
    strategy:
      max-parallel: 16
      matrix:
        type: ["huge"]
        index:
          ["00", "01", "02", "03"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2147483647

      - name: Restore cached results
        if: ${{ !inputs.ignore_prev_result }}
        uses: actions/cache/restore@v4
        id: restore-cached-results
        with:
          path: ${{github.workspace}}/merged-result.json
          key: ${{ runner.os }}-verify-result-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-verify-result-

      - name: Download verify_files.json
        uses: competitive-verifier/actions/download-verify-artifact@v2
        with:
          artifact-name: ${{ runner.os }}-verify-files-${{ matrix.type }}-json

      - name: Set up competitive-verifier
        uses: competitive-verifier/actions/setup@v2
        with:
          package: competitive-verifier==3.3.0.dev0 
          cache-pip: true

      - name: Verify
        uses: competitive-verifier/actions/verify@v2
        with:
          destination: ${{runner.temp}}/result-${{matrix.type}}.json
          split-size: ${{ env.SPLIT_SIZE }}
          split-index: ${{ matrix.index }}
          timeout: 1800
          prev-result: ${{ steps.restore-cached-results.outputs.cache-hit && 'merged-result.json' || ''}}
        env:
          YUKICODER_TOKEN: ${{secrets.YUKICODER_TOKEN}}

      - name: Upload result artifact
        uses: actions/upload-artifact@v4
        with:
          name: Result-${{ runner.os }}-${{ matrix.type }}-${{ matrix.index }}
          path: ${{runner.temp}}/result.json
          retention-days: 1
